"""add artist genre year views

Revision ID: 50df9eb3b223
Revises: fab36b365186
Create Date: 2026-01-09 16:56:03.644372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50df9eb3b223'
down_revision = 'fab36b365186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('artist', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('release_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('release_year')
        batch_op.drop_column('genre')
        batch_op.drop_column('artist')
        batch_op.drop_column('views')

    # ### end Alembic commands ###
