"""nullable = False update:


Revision ID: f4fba82a8c3e
Revises: 50df9eb3b223
Create Date: 2026-01-09 17:38:29.165961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fba82a8c3e'
down_revision = '50df9eb3b223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('artist',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('release_year',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('release_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
